---
- name: Include amnezia wireguard server deployment
  ansible.builtin.include_role:
    name: awg
  vars:
    awg_template: awg-server.conf.j2
    awg_port: stun

- name: Include Certbot SSL certificate management tasks
  ansible.builtin.include_tasks: certbot.yml

- name: Include Nginx web server deployment and security tasks
  ansible.builtin.include_tasks: nginx.yml

- name: Include plug page deployment tasks
  ansible.builtin.include_tasks: plug.yml

- name: Include ntfy notification server deployment tasks
  ansible.builtin.include_tasks: ntfy.yml
