---
- name: Install nginx
  ansible.builtin.apt:
    pkg:
      - nginx
      - libnginx-mod-http-lua
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Create maps folder
  ansible.builtin.file:
    path: /etc/nginx/maps
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Check if user agents map exist
  ansible.builtin.stat:
    path: /etc/nginx/maps/bad_user_agents.map
  register: waf_deploy_bad_user_agents_file

- name: Update user agents map
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/awesfdawe/nginx-misc/refs/heads/main/bad_user_agents.map
    dest: /etc/nginx/maps/bad_user_agents.map
    owner: root
    group: root
    mode: "0644"
  when: not waf_deploy_bad_user_agents_file.stat.exists
  become: true

- name: Install service for user agents map update
  ansible.builtin.copy:
    src: nginx/update_bad_user_agents_map.service
    dest: /etc/systemd/system/update_bad_user_agents_map.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Install timer for user agents map auto update
  ansible.builtin.copy:
    src: nginx/update_bad_user_agents_map.timer
    dest: /etc/systemd/system/update_bad_user_agents_map.timer
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable timer
  ansible.builtin.systemd_service:
    name: update_bad_user_agents_map.timer
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Install crowdsec nginx bouncer
  ansible.builtin.apt:
    name: crowdsec-nginx-bouncer
    update_cache: true
    cache_valid_time: 3600
  notify: Restart Nginx
  become: true

- name: Install appsec crowdsec collections
  ansible.builtin.command:
    cmd: "cscli collections install {{ item }}"
    creates: "/etc/crowdsec/collections/{{ item | basename }}.yaml"
  loop:
    - crowdsecurity/appsec-virtual-patching
    - crowdsecurity/appsec-generic-rules
    - crowdsecurity/nginx
  notify: Reload Crowdsec
  become: true

- name: Setup few crowdsec acquis # replace with fileglob or something
  ansible.builtin.copy:
    src: crowdsec/{{ item }}.yaml
    dest: /etc/crowdsec/acquis.d/{{ item }}.yaml
    owner: root
    group: root
    mode: "0644"
  loop:
    - appsec
    - nginx
  notify: Restart Crowdsec
  become: true

- name: Set right appsec settings
  community.general.ini_file:
    path: /etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    owner: root
    group: root
    mode: "0644"
    create: false
  loop:
    - { key: APPSEC_URL, value: http://127.0.0.1:7422 }
    - { key: APPSEC_FAILURE_ACTION, value: deny }
  notify: Restart Nginx
  become: true

- name: Update Nginx Config
  ansible.builtin.template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true

- name: Update main Nginx snippet
  ansible.builtin.template:
    src: nginx/proxy-snippet.conf.j2
    dest: /etc/nginx/snippets/proxy.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true

- name: Add Global fallback
  ansible.builtin.template:
    src: nginx/sites/global.conf.j2
    dest: /etc/nginx/conf.d/global.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true

- name: Enable nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
  become: true

- name: Allow http/https traffic
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - http
    - https
  become: true
