---
- name: Install nginx
  ansible.builtin.apt:
    pkg:
      - nginx
      - libnginx-mod-http-lua
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Update Nginx Config
  ansible.builtin.template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true

- name: Update main Nginx snippet
  ansible.builtin.template:
    src: nginx/proxy-snippet.conf.j2
    dest: /etc/nginx/snippets/proxy.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true

- name: Enable nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
  become: true

- name: Add Global fallback
  ansible.builtin.template:
    src: nginx/sites/global.conf.j2
    dest: /etc/nginx/conf.d/global.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true

- name: Allow http/https traffic
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - http
    - https
  become: true
