---
- name: Configure ntfy package repository
  ansible.builtin.deb822_repository:
    name: ntfy
    types: deb
    uris: https://archive.ntfy.sh/apt
    suites: stable
    components: main
    signed_by: https://archive.ntfy.sh/apt/keyring.gpg
  notify: Update apt cache
  become: true

- name: Flush handlers now
  ansible.builtin.meta: flush_handlers

- name: Install ntfy application package
  ansible.builtin.apt:
    name: ntfy
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Deploy ntfy server configuration file
  ansible.builtin.template:
    src: ntfy-server.yml.j2
    dest: /etc/ntfy/server.yml
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Ensure required cache and state directories exist for ntfy
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: _ntfy
    group: _ntfy
    mode: "0755"
  loop:
    - /var/cache/ntfy/attachments
    - /var/lib/ntfy
  become: true

- name: Enable and start ntfy messaging service
  ansible.builtin.systemd_service:
    name: ntfy
    enabled: true
    state: started
  become: true

- name: Deploy Nginx virtual host configuration for ntfy
  ansible.builtin.template:
    src: nginx/sites/ntfy.conf.j2
    dest: /etc/nginx/conf.d/ntfy.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx
  become: true
