---
- name: Install wireguard
  ansible.builtin.apt:
    pkg:
      - wireguard
      - wireguard-tools
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install sever wg config
  ansible.builtin.template:
    src: templates/wireguard-server.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart Wireguard
  become: true

- name: Enable and start wireguard service
  ansible.builtin.systemd_service:
    name: wg-quick@wg0
    enabled: true
    state: started
  become: true

- name: Allow WireGuard traffic through Firewalld
  ansible.posix.firewalld:
    service: wireguard
    permanent: true
    state: enabled
    immediate: true
  become: true
