---
- name: Install unattended-upgrades apt-listchanges
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - apt-listchanges
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Enable and start autoupdate service
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    enabled: true
    state: started
  become: true
