---
- name: Install essential packages
  ansible.builtin.apt:
    pkg:
      - btop
      - duf
      - fzf
      - bat
      - lnav
      - lsof
      - rsync
      - curl
      - wget
      - jq
      - zip
      - unzip
      - p7zip-full
      - "linux-headers-{{ {'x86_64': 'amd64', 'aarch64': 'arm64', 'armv7l': 'armhf', 'i686': 'i386'}.get(ansible_architecture, ansible_architecture) }}"
    update_cache: true
    cache_valid_time: 3600
  become: true
