---
- name: Install firewalld
  ansible.builtin.apt:
    name: firewalld
    update_cache: true
  become: true

- name: Enable and start firewalld service
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: true
    state: started
  become: true
