---
- name: Include Firewalld installation and configuration tasks
  ansible.builtin.include_tasks: firewalld.yml

- name: Include CrowdSec security engine installation tasks
  ansible.builtin.include_tasks: crowdsec.yml

- name: Include automatic software updates setup tasks
  ansible.builtin.include_tasks: autoupdate.yml

- name: Include essential utility packages installation tasks
  ansible.builtin.include_tasks: essential_packages.yml

- name: Include Micro text editor installation and configuration tasks
  ansible.builtin.include_tasks: micro.yml
