- name: Install Micro text editor package
  ansible.builtin.apt:
    name: micro
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure configuration directory for Micro editor exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/micro"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0755"

- name: Configure terminal clipboard support in Micro settings
  ansible.builtin.copy:
    dest: "{{ ansible_facts['user_dir'] }}/.config/micro/settings.json"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0644"
    content: |
      {
          "clipboard": "terminal"
      }
