---
- name: Waf server
  hosts: homelab

  tasks:
    - name: Verify that the host is running Debian 13
      ansible.builtin.fail:
        msg: >
          {{ ansible_facts["distribution"] }} is not supported by these playbook.
          Only Debian 13 are supported.
      when: >
        ansible_facts["distribution"] != "Debian" or
        ansible_facts["distribution_major_version"] != "13"

    - name: Include Homelab deployment role
      ansible.builtin.include_role:
        name: homelab
