---
- name: Waf server
  hosts: waf

  tasks:
    - name: Checking if the server is running Debian 13
      ansible.builtin.fail:
        msg: >
          {{ ansible_facts["distribution"] }} is not supported by these playbook.
          Only Debian 13 are supported.
      when: >
        ansible_facts["distribution"] != "Debian" or
        ansible_facts["distribution_major_version"] != "13"

    - name: Main role
      ansible.builtin.include_role:
        name: waf_deploy
